sudo: required
language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
jdk:
  - oraclejdk8
scala:
  - 2.11.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y socat
script:
  - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
