sudo: false
language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
jdk:
  - oraclejdk8
scala:
  - 2.11.8
script:
  - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"